# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UAVPrepareProcessing
                                 A QGIS plugin
 This plugin examines height properties on a DSM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-03-09
        copyright            : (C) 2023 by Jessika Lönn
        email                : jessika.lonn@gu.se
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Jessika Lönn'
__date__ = '2023-03-09'
__copyright__ = '(C) 2023 by Jessika Lönn'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UAVPrepareProcessing class from file UAVPrepareProcessing.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .uav_preparer_processing import UAVPrepareProcessingPlugin
    return UAVPrepareProcessingPlugin()
